### ISSUE TITLE
Please add support for Xiaomi R3G, ZTE 8820s and ZTE 8820v2

### ISSUE THREAD

**Issue by newmem12** [HiGarfield/lede-17.01.4-Mod#10]
Hi HiGarfield, please add support for Xiaomi R3G, ZTE 8820s and ZTE 8820v2
Thank you!

**Comment by HiGarfield** [comment]
I'm sorry, but I cannot complete the support for the mentioned models. Firstly, I don't have access to the specific models you mentioned. Secondly, the NAND driver in lede 17.01 is broken, which only allows for reading and not writing. As a result, it is not possible to save any configuration.
