### ISSUE TITLE
[Security] Workflow build-lede-tl-wr841-v8-cn.yml is using vulnerable action HiGarfield/action-gh-release

### ISSUE THREAD

**Issue by akulpillai** [HiGarfield/lede-17.01.4-Mod#3]
The workflow build-lede-tl-wr841-v8-cn.yml is referencing action HiGarfield/action-gh-release using references v1. However this reference is missing the commit [2cf5c664505721097376937a6b0bcd26758fefc8](https://github.com/HiGarfield/action-gh-release/commits/2cf5c664505721097376937a6b0bcd26758fefc8) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by HiGarfield** [comment]
> The workflow build-lede-tl-wr841-v8-cn.yml is referencing action HiGarfield/action-gh-release using references v1. However this reference is missing the commit [2cf5c664505721097376937a6b0bcd26758fefc8](https://github.com/HiGarfield/action-gh-release/commits/2cf5c664505721097376937a6b0bcd26758fefc8) which may contain fix to the some vulnerability. The vulnerability fix that is missing by actions version could be related to: (1) CVE fix (2) upgrade of vulnerable dependency (3) fix to secret leak and others. Please consider to update the reference to the action.

Thanks for the suggestion. It has now been upgraded.
