### ISSUE TITLE
tplink固件中led配置问题

### ISSUE THREAD

**Issue by Atrexe** [HiGarfield/lede-17.01.4-Mod#4]
我的路由器是tl-wr886n-v5，使用固件是tl-wr941nd-v6，目前插上发现wan口与lan口灯不会亮，还有就是lan3口一直亮灯，请教一下大佬如何设置led，谢谢。

**Comment by HiGarfield** [comment]
> 我的路由器是tl-wr886n-v5，使用固件是tl-wr941nd-v6，目前插上发现wan口与lan口灯不会亮，还有就是lan3口一直亮灯，请教一下大佬如何设置led，谢谢。

要修改 ar71xx 里面的机型定义 .c 文件的。我添加了 tl-w885n-v1。刷这个版本的话，灯应该是对的。

**Comment by Atrexe** [comment]
ar71xx里面的机型定义.c文件在哪里，没有看到，我也想知道是怎么修改。

**Comment by HiGarfield** [comment]
> ar71xx里面的机型定义.c文件在哪里，没有看到，我也想知道是怎么修改。

你看我的这个commit就知道了 https://github.com/HiGarfield/lede-17.01.4-Mod/commit/fa4d95bdba9379daf32166a6f8893de1de7ed4fb

**Comment by HiGarfield** [comment]
> ar71xx里面的机型定义.c文件在哪里，没有看到，我也想知道是怎么修改。

你看我这个commit就知道了https://github.com/HiGarfield/lede-17.01.4-Mod/commit/c9ee89ef0a2ea23aafd5a0dc8d50217c8bde6121

**Comment by Atrexe** [comment]
好的，谢谢哥们，方便留q吗？

**Comment by HiGarfield** [comment]
抱歉，QQ不公开。

**Comment by Atrexe** [comment]
哦！哥们，有必要怎么保密吗？我就问几个问题呢！

**Comment by Atrexe** [comment]
> > ar71xx里面的机型定义.c文件在哪里，没有看到，我也想知道是怎么修改。
> 
> 你看我这个commit就知道了[c9ee89e](https://github.com/HiGarfield/lede-17.01.4-Mod/commit/c9ee89ef0a2ea23aafd5a0dc8d50217c8bde6121)

不知道使用你的源码，放入github会不会被封。

**Comment by HiGarfield** [comment]
> > > ar71xx里面的机型定义.c文件在哪里，没有看到，我也想知道是怎么修改。
> > 
> > 
> > 你看我这个commit就知道了[c9ee89e](https://github.com/HiGarfield/lede-17.01.4-Mod/commit/c9ee89ef0a2ea23aafd5a0dc8d50217c8bde6121)
> 
> 不知道使用你的源码，放入github会不会被封。

 我反正没被封。具体什么规则封，我也不知道。

**Comment by Atrexe** [comment]
> 

你的源码是手动上传，然后自己修改配置的，最后编译的，需要修改什么哪些。

**Comment by HiGarfield** [comment]
> 

我的是源码和编译的yml在同一个repo里的。你的应该是git clone然后编译的，说白了就是repo里没源码，纯跑编译的，这种被封的可能性很大。

**Comment by HiGarfield** [comment]
> > 
> 
> 你的源码是手动上传，然后自己修改配置的，最后编译的，需要修改什么哪些。

在本地全部配置好，直接完整可编译的源码push上去。在线配置的，必封。

**Comment by Atrexe** [comment]
> > > 
> > 
> > 
> > 你的源码是手动上传，然后自己修改配置的，最后编译的，需要修改什么哪些。
> 
> 在本地全部配置好，直接完整可编译的源码push上去。在线配置的，必封。

主要不是很懂，看来需要大佬带带指导指导...

**Comment by HiGarfield** [comment]
> > > > 
> > > 
> > > 
> > > 你的源码是手动上传，然后自己修改配置的，最后编译的，需要修改什么哪些。
> > 
> > 
> > 在本地全部配置好，直接完整可编译的源码push上去。在线配置的，必封。
> 
> 主要不是很懂，看来需要大佬带带指导指导...

你自己机器上搭好完整的编译环境，然后make menuconfig，就生成好了.config文件，然后就push上去就行了。github Actions的workflow定义文件（yml文件）自己写。包括环境搭建、编译、上传固件等步骤。具体写法可以参考官方文档 https://docs.github.com/en/actions

**Comment by Atrexe** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 你的源码是手动上传，然后自己修改配置的，最后编译的，需要修改什么哪些。
> > > 
> > > 
> > > 在本地全部配置好，直接完整可编译的源码push上去。在线配置的，必封。
> > 
> > 
> > 主要不是很懂，看来需要大佬带带指导指导...
> 
> 你自己机器上搭好完整的编译环境，然后make menuconfig，就生成好了.config文件，然后就push上去就行了。github Actions的workflow定义文件（yml文件）自己写。包括环境搭建、编译、上传固件等步骤。具体写法可以参考官方文档 https://docs.github.com/en/actions

大佬不知道fork你仓库的，这样会不会被封。

**Comment by HiGarfield** [comment]
> 

应该是不会封的。我自己的从来没被封过。

**Comment by Atrexe** [comment]
> > 
> 
> 应该是不会封的。我自己的从来没被封过。

好的，我到时候试试。

**Comment by Atrexe** [comment]
你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。

**Comment by HiGarfield** [comment]
> 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。

网上有个教程
https://p3terx.com/archives/github-actions-started-tutorial.html
看不懂的，去查官方文档：
https://docs.github.com/en/actions

download.pl是用aria2加速下载用的。
详细原理见
https://github.com/coolsnowwolf/lede/pull/6526

再细的，自己去研究琢磨了。

**Comment by Atrexe** [comment]
> > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> 
> 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> 
> download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> 
> 再细的，自己去研究琢磨了。

哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？

**Comment by HiGarfield** [comment]
> > > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> > 
> > 
> > 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> > download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> > 再细的，自己去研究琢磨了。
> 
> 哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？

我为了方便代码维护和自动编译写的一些自动脚本。你如果是本机纯手工编译的话，不需要这些。用github actions进行自动编译的话，是需要的。

**Comment by Atrexe** [comment]
> > > > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> > > 
> > > 
> > > 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> > > download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> > > 再细的，自己去研究琢磨了。
> > 
> > 
> > 哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？
> 
> 我为了方便代码维护和自动编译写的一些自动脚本。你如果是本机纯手工编译的话，不需要这些。用github actions进行自动编译的话，是需要的。

CI.yml文件strategy:matrix:target:是对应根目录下con文件夹里的.config文件的吧！

**Comment by HiGarfield** [comment]
> > > > > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> > > > 
> > > > 
> > > > 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> > > > download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> > > > 再细的，自己去研究琢磨了。
> > > 
> > > 
> > > 哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？
> > 
> > 
> > 我为了方便代码维护和自动编译写的一些自动脚本。你如果是本机纯手工编译的话，不需要这些。用github actions进行自动编译的话，是需要的。
> 
> CI.yml文件strategy:matrix:target:是对应根目录下conf文件夹里的.config文件的吧！

对的

**Comment by Atrexe** [comment]
> > > > > > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> > > > > 
> > > > > 
> > > > > 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> > > > > download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> > > > > 再细的，自己去研究琢磨了。
> > > > 
> > > > 
> > > > 哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？
> > > 
> > > 
> > > 我为了方便代码维护和自动编译写的一些自动脚本。你如果是本机纯手工编译的话，不需要这些。用github actions进行自动编译的话，是需要的。
> > 
> > 
> > CI.yml文件strategy:matrix:target:是对应根目录下conf文件夹里的.config文件的吧！
> 
> 对的

你的ci.yml文件里全部机型配置放在一起，actions进行自动编译，全部机型同时排序进行编译了，target里可以指定一个机型吧！这样可以多创建ci.yml文件，对了，ci.yml文件没有其他区域需要修改了吧！默认就可以了，对吧！

**Comment by HiGarfield** [comment]
> > > > > > > 你这个CI.yml文件是怎么配置的，还有download.pl是什么文件，好多外面的链接，这个文件是用来做什么。
> > > > > > 
> > > > > > 
> > > > > > 网上有个教程 https://p3terx.com/archives/github-actions-started-tutorial.html 看不懂的，去查官方文档： https://docs.github.com/en/actions
> > > > > > download.pl是用aria2加速下载用的。 详细原理见 [coolsnowwolf/lede#6526](https://github.com/coolsnowwolf/lede/pull/6526)
> > > > > > 再细的，自己去研究琢磨了。
> > > > > 
> > > > > 
> > > > > 哦！对了，主目录下有几种.sh文件有什么作用，是否可以省略掉的吗？
> > > > 
> > > > 
> > > > 我为了方便代码维护和自动编译写的一些自动脚本。你如果是本机纯手工编译的话，不需要这些。用github actions进行自动编译的话，是需要的。
> > > 
> > > 
> > > CI.yml文件strategy:matrix:target:是对应根目录下conf文件夹里的.config文件的吧！
> > 
> > 
> > 对的
> 
> 你的ci.yml文件里全部机型配置放在一起，actions进行自动编译，全部机型同时排序进行编译了，target里可以指定一个机型吧！这样可以多创建ci.yml文件，对了，ci.yml文件没有其他区域需要修改了吧！默认就可以了，对吧！

这个CI本来就是支持多机型并发编译的。我设计两个批次，纯粹是为了我自己用的机型先编译出来测试，我自己不用的机型后编译。
建议你读懂文档再来改，否则会遇到一堆问题。
我设计的批次编译和并发编译，可以参考的文档都在这里。
https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows

**Comment by Atrexe** [comment]
好的，谢谢我先学习一下。
