### ISSUE TITLE
请问路由器wan与lan数字排序，还有是GPIO号是怎么获取

### ISSUE THREAD

**Issue by Atrexe** [HiGarfield/lede-17.01.4-Mod#5]
路由器wan与lan数字排序是怎么获取
路由器GPIO号是怎么获取
请教一下大佬这种是怎么弄的

**Comment by HiGarfield** [comment]
wan跟lan的直接抄一台wan和lan一致的现有型号就行。

gpio在breed下用btntst和gpio命令进行测试。具体请参阅breed的说明。https://www.right.com.cn/forum/thread-161906-1-1.html

**Comment by Atrexe** [comment]
好的，大佬问问你的项目仓库里的如何添加第三方插件的

**Comment by HiGarfield** [comment]
> 好的，大佬问问你的项目仓库里的如何添加第三方插件的

package目录添加。我习惯添加在package/extra目录下。

**Comment by Atrexe** [comment]
> > 好的，大佬问问你的项目仓库里的如何添加第三方插件的
> 
> package目录添加。我习惯添加在package/extra目录下。

是不是添加到package/extra目录下就可以了，不需要其他命令执行吧！

**Comment by HiGarfield** [comment]
> > > 好的，大佬问问你的项目仓库里的如何添加第三方插件的
> > 
> > 
> > package目录添加。我习惯添加在package/extra目录下。
> 
> 是不是添加到package/extra目录下就可以了，不需要其他命令执行吧！

是的。但值得注意的是，有很多第三方插件，在老的lede中是编译不过的，需要自己修改代码。

**Comment by Atrexe** [comment]
> > > > 好的，大佬问问你的项目仓库里的如何添加第三方插件的
> > > 
> > > 
> > > package目录添加。我习惯添加在package/extra目录下。
> > 
> > 
> > 是不是添加到package/extra目录下就可以了，不需要其他命令执行吧！
> 
> 是的。但值得注意的是，有很多第三方插件，在老的lede中是编译不过的，需要自己修改代码。

老的lede中不兼容，对于小白来说自己修改代码太难了，你是如何把插件文件夹上传到github的，github直接上传的话，不能带文件夹里的文件，难道一个文件一个文件上传吗？

**Comment by HiGarfield** [comment]
> > > > > 好的，大佬问问你的项目仓库里的如何添加第三方插件的
> > > > 
> > > > 
> > > > package目录添加。我习惯添加在package/extra目录下。
> > > 
> > > 
> > > 是不是添加到package/extra目录下就可以了，不需要其他命令执行吧！
> > 
> > 
> > 是的。但值得注意的是，有很多第三方插件，在老的lede中是编译不过的，需要自己修改代码。
> 
> 老的lede中不兼容，对于小白来说自己修改代码太难了，大佬有没有修改的方法呢！方便指点一二吗？你是如何把插件文件夹上传到github的，github直接上传的话，不能带文件夹里的文件，难道一个文件一个文件上传吗？

改代码没有相关专业经历，不可能有捷径，我也不是都能解决的。

玩github不是在网页上传的，都是用git push的。git的入门教程读一下。

**Comment by Atrexe** [comment]
> > > > > > 好的，大佬问问你的项目仓库里的如何添加第三方插件的
> > > > > 
> > > > > 
> > > > > package目录添加。我习惯添加在package/extra目录下。
> > > > 
> > > > 
> > > > 是不是添加到package/extra目录下就可以了，不需要其他命令执行吧！
> > > 
> > > 
> > > 是的。但值得注意的是，有很多第三方插件，在老的lede中是编译不过的，需要自己修改代码。
> > 
> > 
> > 老的lede中不兼容，对于小白来说自己修改代码太难了，大佬有没有修改的方法呢！方便指点一二吗？你是如何把插件文件夹上传到github的，github直接上传的话，不能带文件夹里的文件，难道一个文件一个文件上传吗？
> 
> 改代码没有相关专业经历，不可能有捷径，我也不是都能解决的。
> 
> 玩github不是在网页上传的，都是用git push的。git的入门教程读一下。

哦！好的，谢谢
