### ISSUE TITLE
【请问】服务-域名列表移除

### ISSUE THREAD

**Issue by voyager2u** [HiGarfield/lede-17.01.4-Mod#6]
如图，不需要这个
<img width="178" alt="11" src="https://user-images.githubusercontent.com/73457869/149522719-b4eb78a7-e248-4adf-ab6c-2864da801582.png">
应该在系统-软件包中移除哪一个?

**Comment by HiGarfield** [comment]
> 如图，不需要这个 <img alt="11" width="178" src="https://user-images.githubusercontent.com/73457869/149522719-b4eb78a7-e248-4adf-ab6c-2864da801582.png"> 应该在系统-软件包中移除哪一个?

ipset-lists
