### ISSUE TITLE
ipq806x 编译错误

### ISSUE THREAD

**Issue by hzjnet** [HiGarfield/lede-17.01.4-Mod#6]
环境：
vlsb_release -ra
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

 gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

具体错误如下：
Building backport-include/backport/autoconf.h ... done.
  CC [M]  /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/net/mac80211/rx.o
In file included from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/backport-include/linux/bug.h:3:0,
                 from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/backport-include/linux/kernel.h:4,
                 from include/asm-generic/bug.h:13,
                 from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/backport-include/asm-generic/bug.h:3,
                 from ./arch/arm/include/asm/bug.h:62,
                 from ./arch/arm/include/asm/div64.h:63,
                 from include/linux/math64.h:5,
                 from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/backport-include/linux/math64.h:3,
                 from include/linux/jiffies.h:5,
                 from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/backport-include/linux/jiffies.h:3,
                 from /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/net/mac80211/rx.c:15:
include/linux/bug.h:91:47: warning: 'struct bug_entry' declared inside parameter list will not be visible outside of this definition or declaration
 static inline int is_warning_bug(const struct bug_entry *bug)
                                               ^~~~~~~~~
include/linux/bug.h: In function 'is_warning_bug':
include/linux/bug.h:93:12: error: dereferencing pointer to incomplete type 'const struct bug_entry'
  return bug->flags & BUGFLAG_WARNING;
            ^~
make[9]: *** [scripts/Makefile.build:278: /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/net/mac80211/rx.o] Error 1
make[8]: *** [scripts/Makefile.build:484: /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/net/mac80211] Error 2
make[7]: *** [Makefile:1436: _module_/openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1] Error 2
make[6]: *** [Makefile.build:6: modules] Error 2
make[5]: *** [Makefile.real:93: modules] Error 2
make[4]: *** [Makefile:121: modules] Error 2
make[4]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1'
make[3]: *** [Makefile:572: /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/linux-ipq806x/backports-4.19.237-1/.built] Error 2
make[3]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305220400-ipq806x/package/kernel/mac80211'
make[2]: *** [package/Makefile:109: package/kernel/mac80211/compile] Error 2
make[2]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305220400-ipq806x'
make[1]: *** [package/Makefile:104: /openwrt/lede-17.01.4-Mod-202305220400-ipq806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305220400-ipq806x'
make: *** [/openwrt/lede-17.01.4-Mod-202305220400-ipq806x/include/toplevel.mk:200: world] Error 2

请教是否增加对应补丁

**Comment by HiGarfield** [comment]
This repository is originally modified only for building ar71xx and ramips targets. So I do not guarantee other targets.
Now I have searched for the resolutions to this error and tried to add a patch. Please try the latest commit.

**Comment by hzjnet** [comment]
> This repository is originally modified only for building ar71xx and ramips targets. So I do not guarantee other targets. Now I have searched for the resolutions to this error and tried to add a patch. Please try the latest commit.


continue:
In file included from include/asm-generic/termios.h:5:0,
                 from arch/arm/include/generated/asm/termios.h:1,
                 from ./include/uapi/linux/termios.h:5,
                 from drivers/tty/tty_ioctl.c:10:
include/asm-generic/termios.h: In function 'user_termio_to_kernel_termios':
./arch/arm/include/asm/uaccess.h:232:3: error: implicit declaration of function 'might_fault' [-Werror=implicit-function-declaration]
   might_fault();      \
   ^
include/asm-generic/termios.h:24:6: note: in expansion of macro 'get_user'
  if (get_user(tmp, &termio->c_iflag) < 0)
      ^~~~~~~~
In file included from include/linux/sched.h:17:0,
                 from drivers/tty/tty_ioctl.c:12:
include/linux/kernel.h: At top level:
include/linux/kernel.h:250:20: warning: conflicting types for 'might_fault'
 static inline void might_fault(void) { }
                    ^~~~~~~~~~~
include/linux/kernel.h:250:20: error: static declaration of 'might_fault' follows non-static declaration
In file included from include/asm-generic/termios.h:5:0,
                 from arch/arm/include/generated/asm/termios.h:1,
                 from ./include/uapi/linux/termios.h:5,
                 from drivers/tty/tty_ioctl.c:10:
./arch/arm/include/asm/uaccess.h:232:3: note: previous implicit declaration of 'might_fault' was here
   might_fault();      \
   ^
include/asm-generic/termios.h:24:6: note: in expansion of macro 'get_user'
  if (get_user(tmp, &termio->c_iflag) < 0)
      ^~~~~~~~
cc1: some warnings being treated as errors
make[7]: *** [scripts/Makefile.build:278: drivers/tty/tty_ioctl.o] Error 1
make[6]: *** [scripts/Makefile.build:484: drivers/tty] Error 2

go on?

**Comment by HiGarfield** [comment]
A new patch is submitted. Please try.

However, I would like to be more pessimistic about building for the ipq806x target. There may be dozens or hundreds of problems that still need to be fixed, which may not be easy to fix in the Linux 4.4 kernel.

**Comment by hzjnet** [comment]
> A new patch is submitted. Please try.
> 
> However, I would like to be more pessimistic about building for the ipq806x target. There may be dozens or hundreds of problems that still need to be fixed, which may not be easy to fix in the Linux 4.4 kernel.

thinks;
continue  make log:  
cc -c -DPERL_CORE -D_REENTRANT -D_GNU_SOURCE -fwrapv -fpcc-struct-return -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -Wall pp.c
pp.c: In function 'Perl_pp_crypt':
pp.c:3628:47: error: 'struct crypt_data' has no member named 'current_saltbits'
 3628 |      PL_reentrant_buffer->_crypt_struct_buffer->current_saltbits = 0;
      |                                               ^~
make[4]: *** [makefile:257: pp.o] Error 1
make[4]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305230447-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/host/perl/perl-5.22.1'
make[3]: *** [Makefile:144: /openwrt/lede-17.01.4-Mod-202305230447-ipq806x/build_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/host/perl/perl-5.22.1/.built] Error 2
make[2]: *** [package/Makefile:108: package/feeds/packages/perl/host/compile] Error 2
make[3]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305230447-ipq806x/feeds/packages/lang/perl'
make[2]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305230447-ipq806x'
make[1]: *** [package/Makefile:104: /openwrt/lede-17.01.4-Mod-202305230447-ipq806x/staging_dir/target-arm_cortex-a15+neon-vfpv4_musl-1.1.24_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/openwrt/lede-17.01.4-Mod-202305230447-ipq806x'
make: *** [/openwrt/lede-17.01.4-Mod-202305230447-ipq806x/include/toplevel.mk:200: world] Error 2

go on?

**Comment by HiGarfield** [comment]
I have updated perl. However, it is still **impossible** to be compatible with modern perl-based packages. The only way is to drop extra packages based on perl.

**Comment by hzjnet** [comment]
> I have updated perl. However, it is still **impossible** to be compatible with modern perl-based packages. The only way is to drop extra packages based on perl.

log:

make[2]: Entering directory '/openwrt/lede-17.01.4-Mod-202305250145'
tmp/.config-package.in:64306:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:64306:   symbol PACKAGE_freeswitch depends on PACKAGE_freeswitch-mod-perl
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:65608:   symbol PACKAGE_freeswitch-mod-perl is selected by PACKAGE_freeswitch-mod-verto
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:66456:   symbol PACKAGE_freeswitch-mod-verto depends on PACKAGE_freeswitch
tmp/.config-package.in:64306:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:64306:   symbol PACKAGE_freeswitch depends on PACKAGE_freeswitch-mod-perl
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:65608:   symbol PACKAGE_freeswitch-mod-perl is selected by PACKAGE_freeswitch-mod-verto
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:66456:   symbol PACKAGE_freeswitch-mod-verto depends on PACKAGE_freeswitch

ok but  freeswitch  ,thantks

**Comment by HiGarfield** [comment]
I have updated all Perl packages. I hope to solve the problem.

However, third-party packages may still fail to build. Due to the outdated kernel, libs, and base packages, I am not planning to support any third-party package beyond the official packages within lede 17.01.

**Comment by hzjnet** [comment]
> I have updated all Perl packages. I hope to solve the problem.
> 
> However, third-party packages may still fail to build. Due to the outdated kernel, libs, and base packages, I am not planning to support any third-party package beyond the official packages within lede 17.01.

thanks  ,but this is :feeds/telephony/net/freeswitch

**Comment by HiGarfield** [comment]
> > I have updated all Perl packages. I hope to solve the problem.
> > However, third-party packages may still fail to build. Due to the outdated kernel, libs, and base packages, I am not planning to support any third-party package beyond the official packages within lede 17.01.
> 
> thanks ,but this is :feeds/telephony/net/freeswitch

updated

**Comment by hzjnet** [comment]
> > > I have updated all Perl packages. I hope to solve the problem.
> > > However, third-party packages may still fail to build. Due to the outdated kernel, libs, and base packages, I am not planning to support any third-party package beyond the official packages within lede 17.01.
> > 
> > 
> > thanks ,but this is :feeds/telephony/net/freeswitch
> 
> updated

advice update soft:
$ find bin|grep cjdns
bin/packages/arm_cortex-a15_neon-vfpv4/routing/cjdns_20.2-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/routing/luci-app-cjdns_1.3-5_arm_cortex-a15_neon-vfpv4.ipk
$ find bin|grep bmx7 
bin/packages/arm_cortex-a15_neon-vfpv4/routing/bmx7_r2018122901-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/routing/luci-app-bmx7_0.0-alpha_arm_cortex-a15_neon-vfpv4.ipk
$ find bin|grep boost 
bin/packages/arm_cortex-a15_neon-vfpv4/packages/boost-date_time_1.68.0-6_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/boost-program_options_1.68.0-6_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/boost-system_1.68.0-6_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/boost_1.68.0-6_arm_cortex-a15_neon-vfpv4.ipk
find bin|grep golang
bin/packages/arm_cortex-a15_neon-vfpv4/packages/golang_1.20.2-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/golang-src_1.20.2-1_arm_cortex-a15_neon-vfpv4.ipk

find bin|grep openssl
bin/packages/arm_cortex-a15_neon-vfpv4/base/libopenssl_1.1.1o-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/base/libopenssl-conf_1.1.1o-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/base/openssl-util_1.1.1o-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/base/libustream-openssl_2018-05-22-5322f9db-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/base/wpad-mesh-openssl_2019-08-08-ca8c2bd2-6_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/base/openvpn-openssl_2.4.6-3_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/libarchive-noopenssl_3.2.2-1_arm_cortex-a15_neon-vfpv4.ipk
bin/packages/arm_cortex-a15_neon-vfpv4/packages/libwebsockets-openssl_2.0.3-1_arm_cortex-a15_neon-vfpv4.ipk

**Comment by HiGarfield** [comment]
Updating basic libs or base packages causes build errors of the ancient packages in lede 17.01.

I have tried updating the following packages.
[1] Updating openssl to 1.1 causes endless errors in ancient package sources.
[2] Updating golang leads to a larger binary size of kcptun, thus causing insufficient space left in the flash, which ends up with config not saving problem.

As a result, I reverted these updates and decided to leave them with very old versions.

**Comment by hzjnet** [comment]
> Updating basic libs or base packages causes build errors of the ancient packages in lede 17.01.
> 
> I have tried updating the following packages. [1] Updating openssl to 1.1 causes endless errors in ancient package sources. [2] Updating golang leads to a larger binary size of kcptun, thus causing insufficient space left in the flash, which ends up with config not saving problem.
> 
> As a result, I reverted these updates and decided to leave them with very old versions.

maybe for your information：https://github.com/sdf8057/ipq6000

**Comment by HiGarfield** [comment]
> recursive dependency

Recursive dependency has been resolved.
