### ISSUE TITLE
202306062345 building  ipq806x error

### ISSUE THREAD

**Issue by hzjnet** [HiGarfield/lede-17.01.4-Mod#7]
env:
os
lsb_release -ra
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

log:
checking for arm-openwrt-linux-muslgnueabi-ar... /openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/bin/ar
checking for arm-openwrt-linux-muslgnueabi-lipo... arm-openwrt-linux-muslgnueabi-lipo
checking for arm-openwrt-linux-muslgnueabi-nm... /openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/./gcc/nm
checking for arm-openwrt-linux-muslgnueabi-ranlib... /openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/bin/ranlib
checking for arm-openwrt-linux-muslgnueabi-strip... /openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/bin/strip
checking whether ln -s works... yes
checking for arm-openwrt-linux-muslgnueabi-gcc...  /openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/./gcc/xgcc -B/openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/./gcc/ -B/openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/bin/ -B/openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/lib/ -isystem /openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/include -isystem /openwrt/lede-17.01.4-Mod-202306041824/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/arm-openwrt-linux-muslgnueabi/sys-include   
checking for suffix of object files... configure: error: in `/openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/arm-openwrt-linux-muslgnueabi/libgcc':
configure: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.
make[3]: *** [Makefile:11444: configure-target-libgcc] Error 1
make[3]: Leaving directory '/openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial'
make[2]: *** [Makefile:37: /openwrt/lede-17.01.4-Mod-202306041824/build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/.built] Error 2
make[2]: Leaving directory '/openwrt/lede-17.01.4-Mod-202306041824/toolchain/gcc/initial'
make[1]: *** [toolchain/Makefile:92: toolchain/gcc/initial/compile] Error 2

build_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi/gcc-7.5.0-initial/arm-openwrt-linux-muslgnueabi/libgcc$ cat config.log
pdfdir='${docdir}'
prefix='/openwrt/lede-17.01.4-Mod-202306062345/staging_dir/toolchain-arm_cortex-a15+neon-vfpv4_gcc-7.5.0_musl-1.1.24_eabi'
program_transform_name='s&^&arm-openwrt-linux-muslgnueabi-&'
psdir='${docdir}'
real_host_noncanonical=''
sbindir='${exec_prefix}/sbin'
set_have_cc_tls=''
set_use_emutls=''
sfp_machine_header=''
sharedstatedir='${prefix}/com'
slibdir='$(exec_prefix)/$(host_noncanonical)/lib'
sysconfdir='${prefix}/etc'
target_alias='arm-openwrt-linux-muslgnueabi'
target_noncanonical='arm-openwrt-linux-muslgnueabi'
target_subdir='arm-openwrt-linux-muslgnueabi'
thread_header=''
tm_defines=''
tm_file=''
tmake_file=''
toolexecdir='$(exec_prefix)/$(target_noncanonical)'
toolexeclibdir='$(toolexecdir)/lib'
unwind_header=''
vis_hide=''
with_aix_soname='aix'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "GNU C Runtime Library"
#define PACKAGE_TARNAME "libgcc"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "GNU C Runtime Library 1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL "http://www.gnu.org/software/libgcc/"

configure: exit 1

**Comment by HiGarfield** [comment]
This repo is not compatible with GCC 10. Please downgrade to GCC 9.

**Comment by hzjnet** [comment]
> This repo is not compatible with GCC 10. Please downgrade to GCC 9.

thanks.  it,s my bad,sorry
