### ISSUE TITLE
请教一下Makefile中PKG_MIRROR_HASH具体是如何计算出来的

### ISSUE THREAD

**Issue by qwerttvv** [HiGarfield/lede-17.01.4-Mod#9]
PKG_NAME:=smartdns
PKG_VERSION:=1.2024.10
PKG_RELEASE:=1

PKG_SOURCE_PROTO:=git
PKG_SOURCE_URL:=https://www.github.com/pymumu/smartdns.git
PKG_SOURCE_VERSION:=40dc9eceb78ac558b235a128241b1a4d2819f15f
PKG_MIRROR_HASH:=5b80c76c55f0d77106faff04056c1568b074491197818375c01a211847296b49

这里的PKG_MIRROR_HASH，我看文档是从 https://www.github.com/pymumu/smartdns.git 打包一个tar.xz后计算sha256，但是这个tar.xz请问下是如何打包的，我试了很久，最终的hash都对不上

或者说这个PKG_MIRROR_HASH是依靠什么脚本或者其它工具生成的？我想学习下这个值的生成过程

不要skip，要这个值的生成过程

尝试过很多方法，例如下面的

$SHA_smartdns已经获取后，相关流程如下，哪里不对…或者说正确方法是啥

          git clone https://www.github.com/pymumu/smartdns.git smartdns-$(date +1.%Y.%m.%d-%H)
          cd smartdns-$(date +1.%Y.%m.%d-%H)
          git checkout $SHA_smartdns
          git submodule update --init --recursive
          echo "TAR_TIMESTAMP=$(git log -1 --format='@%ct')" >> $GITHUB_ENV
          rm -rf .git
然后

          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name $$$${TAR_TIMESTAMP:+--mtime="$$$$TAR_TIMESTAMP"} -c smartdns-$(date +1.%Y.%m.%d-%H) | xz -zc -7e > ../smartdns-$(date +1.%Y.%m.%d-%H).tar.xz
          echo "PKG_MIRROR_HASH=$(sha256sum ../smartdns-$(date +1.%Y.%m.%d-%H).tar.xz | cut -d ' ' -f1)" >> $GITHUB_ENV

之后改Makefile准备去openwrt/gh-action-sdk@main运行

          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=$(date +1.%Y.%m.%d-%H)/" Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$SHA_smartdns/" Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=$PKG_MIRROR_HASH/" Makefile

或者其中

    tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name ${TAR_TIMESTAMP:+--mtime="$TAR_TIMESTAMP"} -c smartdns-$(date +1.%Y.%m.%d-%H) | xz -zc -7e > ../smartdns-$(date +1.%Y.%m.%d-%H).tar.xz

都不对

**Comment by HiGarfield** [comment]
First, comment out the `PKG_MIRROR_HASH` line in `Makefile` (or alternatively set `PKG_MIRROR_HASH:=skip`), and prepare the `.config` file using `make menuconfig`, ensuring that smartdns is selected.

Then run the following command.
```
make package/extra/smartdns/download && sha256sum dl/smartdns-*.tar.xz
```

**Comment by qwerttvv** [comment]
Thanks! 

I'm using openwrt/gh-action-sdk 
And this tool can't set PKG_MIRROR_HASH to skip
If it's set to skip it'll report an error and exit...
